<a href="https://colab.research.google.com/github/sri976/generative-AI-2025/blob/main/2033_W1_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Table 1: YActual vs. YPred
Y_actual = [20, 30, 40, 50, 60]
Y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

# Function to calculate error metrics from scratch
def calculate_metrics_from_scratch(y_actual, y_pred):
    n = len(y_actual)
    absolute_errors = [abs(y_a - y_p) for y_a, y_p in zip(y_actual, y_pred)]
    squared_errors = [(y_a - y_p) ** 2 for y_a, y_p in zip(y_actual, y_pred)]

    mae = sum(absolute_errors) / n
    mse = sum(squared_errors) / n
    rmse = mse ** 0.5

    return mae, mse, rmse

# Calculate metrics from scratch
mae_scratch, mse_scratch, rmse_scratch = calculate_metrics_from_scratch(Y_actual, Y_pred)

# Calculate metrics using libraries
mae_lib = mean_absolute_error(Y_actual, Y_pred)
mse_lib = mean_squared_error(Y_actual, Y_pred)
# Calculate RMSE by taking the square root of MSE
rmse_lib = np.sqrt(mse_lib)  # Calculate RMSE using NumPy

# Display results
print("Error Metrics Calculated From Scratch:")
print(f"Mean Absolute Error (MAE): {mae_scratch}")
print(f"Mean Squared Error (MSE): {mse_scratch}")
print(f"Root Mean Squared Error (RMSE): {rmse_scratch}")

print("\nError Metrics Calculated Using Libraries:")
print(f"Mean Absolute Error (MAE): {mae_lib}")
print(f"Mean Squared Error (MSE): {mse_lib}")
print(f"Root Mean Squared Error (RMSE): {rmse_lib}")


Error Metrics Calculated From Scratch:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127

Error Metrics Calculated Using Libraries:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


In [14]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
y_a = [0, 0, 1, 1, 2, 0, 0, 1, 0, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 2]
y_p = [0, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2]
def calc_acc(y_a, y_p):
    c = sum([1 for a, p in zip(y_a, y_p) if a == p])
    return c / len(y_a)
def calc_cm(y_a, y_p, n_c):
    m = np.zeros((n_c, n_c), dtype=int)
    for a, p in zip(y_a, y_p):
        m[a][p] += 1
    return m
n_c = len(set(y_a))
acc = calc_acc(y_a, y_p)
cm = calc_cm(y_a, y_p, n_c)
lib_acc = accuracy_score(y_a, y_p)
lib_cm = confusion_matrix(y_a, y_p)
print("Accuracy (from scratch):", acc)
print("Confusion Matrix (from scratch):\n", cm)
print("\nUsing Libraries:")
print("Accuracy (library):", lib_acc)
print("Confusion Matrix (library):\n", lib_cm)

Accuracy (from scratch): 0.8636363636363636
Confusion Matrix (from scratch):
 [[6 0 1]
 [1 6 0]
 [1 0 7]]

Using Libraries:
Accuracy (library): 0.8636363636363636
Confusion Matrix (library):
 [[6 0 1]
 [1 6 0]
 [1 0 7]]
